version: 2

sources:
  - name: tpch_sf10
    description: sales data
    database: snowflake_sample_data
    schema: tpch_sf10
    tables:
      - name: lineitem
      - name: customer
      - name: nation
      - name: orders
      - name: part
      - name: partsupp      
      - name: region
      - name: supplier    